version: "3.7"

services:
  app:
    build:
      args:
        container_project_path: /var/www/html/
        host_project_path: ./workspace/
        uid: 1000
        user: $USER
      context: .
      dockerfile: ./Dockerfile
    image: app-php-apache
    container_name: npca-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - network-name
      
  db:
    image: mysql:8.0
    container_name: db-npca
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - network-name

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container-name
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8081:80
    networks:
      - network-name

  nginx:
    image: nginx:alpine
    container_name: nginx-container-name
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/npca.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-name

networks:
  network-name:
    driver: bridge
